# 中文汉化清单 -> Cemu wiki 英文条目名 的人工映射。
# 来源：oldmanemu.org / bbs.xqemu.cn 的「WIIU中文游戏全集」(133 条，去重后 62 个标题)
ZH_TO_EN = {
 'FC红白机复古游戏合集':'NES Remix 1',
 'Wii派对U':'Wii Party U',
 '暗黑血统 战神版':'Darksiders II',
 '傲气雄鹰 周年版':'Another World 20th Anniversary Edition',
 '北欧巨神瓦尔哈拉 约顿':'Jotun: Valhalla Edition',
 '铲子骑士':'Shovel Knight',
 '超级马里奥3D世界':'Super Mario 3D World',
 '超级马里奥制造':'Super Mario Maker',
 '超级食肉男孩':'Super Meat Boy',
 '刺客信条3':"Assassin's Creed III",
 '刺客信条4 黑旗':"Assassin's Creed IV: Black Flag",
 '怪物猎人3G HD':'Monster Hunter 3 Ultimate',
 '光之子':'Child of Light',
 '幻影异闻录':'Tokyo Mirage Sessions',
 '看门狗':'Watch Dogs',
 '乐高都市 卧底风云':'LEGO City: Undercover',
 '乐高漫威超级英雄':'LEGO Marvel Super Heroes',
 '乐高侏罗纪世界':'LEGO Jurassic World',
 '雷曼 传奇':'Rayman Legends',
 '猎天使魔女2':'Bayonetta 2',
 '零 濡鸦之巫女':'Project Zero: Maiden of Black Water',
 '马里奥vs大金刚 大家的迷你岛':'Mario vs. Donkey Kong: Tipping Stars',
 '马里奥派对10':'Mario Party 10',
 '马里奥赛车8':'Mario Kart 8',
 '迷失之地':'Trine 2',
 '蘑菇队长 奇诺比奥 宝藏追踪者':'Captain Toad: Treasure Tracker',
 '喷射战士':'Splatoon',
 '皮克敏3':'Pikmin 3',
 '奇异世界 阿比逃亡记 新鲜可口':"Oddworld: New 'n' Tasty!",
 '任天堂大陆':'Nintendo Land',
 '塞尔达传说 风之杖 HD':'The Legend of Zelda: The Wind Waker HD',
 '塞尔达传说 荒野之息':'The Legend of Zelda: Breath of the Wild',
 '塞尔达传说 黄昏公主 HD':'The Legend of Zelda: Twilight Princess HD',
 '生化危机 启示录 HD':'Resident Evil Revelations',
 '我的世界':'Minecraft: Wii U Edition',
 '我的世界 故事模式':"Minecraft: Story Mode",
 '新超级路易吉U':'New Super Luigi U',
 '新超级马里奥兄弟U':'New Super Mario Bros. U',
 '星之卡比 彩虹诅咒':'Kirby and the Rainbow Curse',
 '耀西的毛线世界':"Yoshi's Woolly World",
 '以撒的结合 重生':'The Binding of Isaac: Rebirth',
 '异度之刃X':'Xenoblade Chronicles X',
 '纸片马里奥 彩色喷涂':'Paper Mario: Color Splash',
 '魔法气泡噗哟噗哟俄罗斯方块':'Puyo Puyo Tetris',
 '舞力全开 东方版':'Just Dance 2015',
}
